//error constants
const EC_EMAIL_EXISTS = "EMAIL_EXISTS";

const EC_INVALID_CODE = "INVALID_CODE";

const EC_ALREADY_ENABLED = "ALREADY_ENABLED";

const EC_ALREADY_JOINED = "ALREADY_JOINED";

 
export {
    EC_EMAIL_EXISTS,
    EC_INVALID_CODE,
    EC_ALREADY_ENABLED,
    EC_ALREADY_JOINED
};