//status constants
const SC_OK = 200;

const SC_CREATED = 201;

const SC_NO_CONTENT = 204;

const SC_BAD_REQUEST = 400;

const SC_UNAUTHORIZED = 401;

const SC_FORBIDDEN = 403;

const SC_NOT_FOUND = 404;

const SC_TIME_OUT = 408;

const SC_CONFLICT = 409;

const SC_CLIENT_CLOSED_REQUEST = 499;

const SC_SERVER_ERROR = 500;

export {
    SC_OK,
    SC_CREATED,
    SC_NO_CONTENT,
    SC_BAD_REQUEST,
    SC_UNAUTHORIZED,
    SC_FORBIDDEN,
    SC_NOT_FOUND,
    SC_TIME_OUT,
    SC_CONFLICT,
    SC_CLIENT_CLOSED_REQUEST,
    SC_SERVER_ERROR
};
