CREATE TABLE IF NOT EXISTS Blacklist(
  id INT PRIMARY KEY,
  token VARCHAR(500) NOT NULL,
  expiry TIMESTAMP NOT NULL
);

CREATE SEQUENCE jwtIdSeq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE;

ALTER TABLE ONLY Blacklist ALTER COLUMN id SET DEFAULT nextval('jwtIdSeq'::regclass);